spring:
  datasource:
    username: root
    password: xxxx
    url: jdbc:mysql://localhost:3306/arppl4_spring_student?serverTimezone=Europe/Warsaw&createDatabaseIfNotExist=true
  jpa:
    hibernate:
      ddl-auto: update
server:
  port: 8089